spring.application.name=gameStore
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/gamestore
spring.datasource.username=gamestore
spring.datasource.password=gamestore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true